### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by pavanagrawal123** [bcwik9/robinhood-on-rails#1]
Hi! I just found this project and it looks awesome!

Are there any instructions for running it?

**Comment by bcwik9** [comment]
Hey, thanks for your interest. This relies on an unpublished API provided by [robinhood](https://robinhood.com). It's a web dashboard built on Ruby on Rails. You can install rvm (and rails) by visiting https://rvm.io/rvm/install.
If you already have ruby on rails set up, simply clone this project. Then run the basic steps to run the project like you would any other rails project:
* `bundle install`
* `bundle exec rake db:create db:migrate`
  * it doesn't actually rely on a database, but rails might complain that it isnt set up
* then, start the web server:
  * `bundle exec rails server`
* navigate to http://localhost:3000/ in whatever webrowser you use (I use chrome, for instance), and you should see a login screen:
![image](https://cloud.githubusercontent.com/assets/508449/24683768/3c277326-196f-11e7-8687-c3785c2bdd1a.png)

Simply enter your login info, and you'll be presented with a dashboard which is your Robinhood portfolio:
![image](https://cloud.githubusercontent.com/assets/508449/24683808/751d6dde-196f-11e7-9a92-a7e7f95dd3e9.png)

**Comment by pavanagrawal123** [comment]
Hi! I got it running but I get a CookieOverflow Error upon logging in.... What logs can I provide that would be helpful for debugging?

**Comment by bcwik9** [comment]
I just pushed some changes that make it so it relies less on session/cookie, so pull those down and give it another go.

**Comment by pavanagrawal123** [comment]
Yep! Works now! Where is the return column on the homepage pulling from? It seems random.

**Comment by bcwik9** [comment]
The return column is an attempt to replicate the "Total Return" for that stock since you bought it. It's supposed to be the same value as what you see in the Robinhood app when you click a stock you own to go in to the details, and scroll down a bit, and it'll show you your shares, total equity value, average purchase cost, TOTAL RETURN, and today's return.

Robinhood doesn't seem to provide these values directly through their API though; I had to calculate them myself. Additionally, the values I calculated for that column are different than what Robinhood shows in the app. However, this is something I'm still not sure about. My calculations for total return on a stock are (anyone feel free to correct me if this is the wrong approach):
```
total_return_for_a_given_stock = current_equity_value +  total_cost_of_sell_orders - total_cost_of_buy_orders
```

**Comment by pavanagrawal123** [comment]
Ok! I see thanks for the detailed response! The new changes are awesome! If it's possible can you add a column with the Robinhood version of total return? I think that might be a bit more useful than total return on that stock.

**Comment by bcwik9** [comment]
@pavanagrawal123 the values seem to be lining up for me from my changes last night. the "todays return" column is how much the total value of your shares has changed, and the "return" column is the same value as the "total return" when looking at a stock's details in the robinhood app

**Comment by pavanagrawal123** [comment]
Yep! It's working perfectly! Do you need any stylesheet help? I would be happy to do that!

**Comment by bcwik9** [comment]
Do you mean refactoring the stylesheets, or styling in general? I've been changing stuff pretty quickly so it's definitely a little messy

**Comment by pavanagrawal123** [comment]
I just meant styling in general!

**Comment by bcwik9** [comment]
Sure, if you want to contribute just make fork/make a pull request and we can review stuff
