### ISSUE TITLE
Putting stop loss on position removes it from portfolio

### ISSUE THREAD

**Issue by cdtweb** [bcwik9/robinhood-on-rails#16]
Putting a stop loss on a position removes it from the portfolio.

**Comment by bcwik9** [comment]
Thanks for posting! I'll take a look.

**Comment by bcwik9** [comment]
do you know if the stop loss was being executed when you were looking at it? I created a couple stop losses today and wasn't able to recreate the bug

**Comment by cdtweb** [comment]
@bcwik9 I think you are right. I have 2 positions on stop loss and they are appearing in the portfolio as expected. I apologize for wasting your time on this. Thank you for your help and for this wonderful app.

**Comment by bcwik9** [comment]
No worries! Stop losses and other advanced orders are still something that I'm working on.

**Comment by cdtweb** [comment]
Man, I wish I knew ruby better so I could help you out!
