### ISSUE TITLE
Question: Auto-refresh rate?

### ISSUE THREAD

**Issue by drew-wallace** [bcwik9/robinhood-on-rails#2]
I'm also making a Robinhood client (for Windows 10), and ran into an api call limit while testing. What refresh rate do you use when auto refreshing? I want to avoid the call limit so the user doesn't run into any issues with normal use.

**Comment by bcwik9** [comment]
the portfolio portion refreshes every 15 seconds and the positions/watchlist refresh every 20 seconds. however each of those sections makes various calls to the API (for quotes, account information, etc), so it's not exactly a single call to the API. Those calls are unthrottled.

**Comment by drew-wallace** [comment]
Are you requesting historical data within those calls at all?

**Comment by bcwik9** [comment]
I request historical data for portfolio history every 5 minutes, since that's the update timeframe (the interval for the span of a day is 5 minutes)

**Comment by drew-wallace** [comment]
Gotcha. Thanks!
