### ISSUE TITLE
Split stock does not reflect in portfolio

### ISSUE THREAD

**Issue by citizen85081** [bcwik9/robinhood-on-rails#20]
When a stock splits(2:1) the interface shows a loss and only one share. On my phone I see myself as holding two shares.

**Comment by bcwik9** [comment]
Unfortunately I don't have support for splits yet, it's functionality I still need to tackle

**Comment by bcwik9** [comment]
I just merged a branch with split support to master. Pull down the latest code and try it out, hopefully it should fix your issue. Lemme know how it goes!

**Comment by citizen85081** [comment]
Hello,
Just gave it a spin. It looks to be reflecting correctly now. Thank you!
