### ISSUE TITLE
Return with sells taking past positions into consideration?

### ISSUE THREAD

**Issue by cdtweb** [bcwik9/robinhood-on-rails#27]
Basically, I held $VSLR previously but I sold it for a gain. I just bought in again today and the return with sells is very wrong. 

I destroyed my docker instance, pulled the latest repository update, and created the instance again.

Here is a screenshot of my position:
https://www.dropbox.com/s/c0ccgjn8sm9zrgs/Screen%20Shot%202017-07-03%20at%2010.45.30%20AM.png?dl=0

**Comment by bcwik9** [comment]
I'd only be able to debug if I saw the buy/sell orders so I could see what it's supposed to be. `return with sells` does account for all previous positions, which is why it's positive since you held it and sold for a gain

**Comment by bcwik9** [comment]
The `sell` column should match the values of the robinhood app, since it does not take past positions in to consideration. I'm going to close this for now since it seems to be working correctly
