### ISSUE TITLE
Fractional prices are being rounded

### ISSUE THREAD

**Issue by cdtweb** [bcwik9/robinhood-on-rails#28]
https://www.dropbox.com/s/pizq6qt0covs86a/Screen%20Shot%202017-07-03%20at%2011.00.44%20AM.png?dl=0

https://www.dropbox.com/s/lsb3sz7c82xdtdg/Screen%20Shot%202017-07-03%20at%2011.00.51%20AM.png?dl=0

This is verify noticeable for penny stocks like $DCTH

**Comment by bcwik9** [comment]
Thanks for posting, it seems like a bug. I'll take a look
