### ISSUE TITLE
ActionController::InvalidAuthenticityToken

### ISSUE THREAD

**Issue by geanttechnology** [bcwik9/robinhood-on-rails#3]
Hi am having this issue when trying to login:

def handle_unverified_request
          raise ActionController::InvalidAuthenticityToken
        end
      end
    end

Am I missing on a step?

**Comment by geanttechnology** [comment]
By the way, it is worth noting that I only receive that issue when I use https. Is there something I need to change to make https work

**Comment by bcwik9** [comment]
Have you done the steps listed in https://www.pluralsight.com/guides/ruby-ruby-on-rails/using-https-with-ruby-on-rails, or have used HTTPS before? This project as it is right now is not set up for HTTPS.

**Comment by bcwik9** [comment]
Closing this for now, feel free to reopen if there are still issues.
