### ISSUE TITLE
Buying power remains $0.00

### ISSUE THREAD

**Issue by kyleboddy** [bcwik9/robinhood-on-rails#31]
Buying power seems to constantly read $0.00 regardless of cash available or deposits. This happens with an account with no Robinhood gold.

![image](https://user-images.githubusercontent.com/746351/29288840-34fca750-80ef-11e7-91cd-82f9b0a67f95.png)

**Comment by kyleboddy** [comment]
(The official iOS app has the correct buying power, BTW)

**Comment by bcwik9** [comment]
@kyleboddy do you have pending orders that haven't been executed yet?

**Comment by kyleboddy** [comment]
No pending orders:

![image](https://user-images.githubusercontent.com/746351/29289251-991d1ba6-80f0-11e7-9f6a-ec970d5a98d3.png)

I do have pending deposits, however, but they are and were available for purchasing equities right away.

**Comment by kyleboddy** [comment]
I used the Robinhood API to pull the responses and this is the content of results['margin_balances']:

`"margin_balances":{"day_trade_buying_power":"1304.0125","start_of_day_overnight_buying_power":"-396.0900","overnight_buying_power_held_for_orders":"0.0000","cash_held_for_orders":"0.0000","created_at":"2017-04-19T07:02:31.027035Z","unsettled_debit":"1295.6400","start_of_day_dtbp":"603.9000","day_trade_buying_power_held_for_orders":"0.0000","overnight_buying_power":"4.3600","marked_pattern_day_trader_date":null,"cash":"-795.6400","unallocated_margin_cash":"4.3600","updated_at":"2017-08-14T19:52:49.151954Z","cash_available_for_withdrawal":"0.0000","margin_limit":"0.0000","outstanding_interest":"0.0000","uncleared_deposits":"800.0000","unsettled_funds":"0.0000","day_trade_ratio":"0.25","overnight_ratio":"1.00"}`

The iOS app reports the `overnight_buying_power` variable as the Buying Power in the app, I believe, regardless of unsettled funds (that are available instantly; if the markets were open, I could definitely use that $4.36 to purchase equities."

Not sure if there should be two fields in the Robinhood on Rails app to adjust for this, or to switch entirely, or what the best route going forward is, but that seems to be the reason for the discrepancy in Buying Power between the app and Robinhood on Rails.

**Comment by bcwik9** [comment]
Thanks for the help @kyleboddy . I just patched master and instant accounts should have the correct buying power displayed. Feel free to reopen if the bug persists.
