### ISSUE TITLE
Robinhood changed Login API endpoint

### ISSUE THREAD

**Issue by in4sometech** [bcwik9/robinhood-on-rails#39]
The Login URL has been changed and the auth token process have been changed as it now uses Oauth2 and Bearer.  Any chance the code will reflect these changes  soon?. I am trying from my end, but it seems I need to change more than few places. Thanks

**Comment by in4sometech** [comment]
At last, I think I temporarily fixed the Login API. Not requesting a Pull because the code may not be clean as I changed few lines and is my first Ruby code changes.
 
FYI:- 
https://github.com/in4sometech/robinhood-on-rails/tree/Login-API-Fix
![image](https://user-images.githubusercontent.com/20666919/47027041-8a55c880-d11b-11e8-8bc4-c898a4edb6d5.png)

**Comment by bcwik9** [comment]
Thanks for posting! I have a login auth change in my crypto branch but that isn't in master yet

**Comment by bcwik9** [comment]
I updated the master branch today to support new oauth logins.

**Comment by in4sometech** [comment]
> I updated the master branch today to support new oauth logins.

Thank You, Just tested it. :)

**Comment by frakman1** [comment]
Does this still work? I was unable to login with the master code today

**Comment by bcwik9** [comment]
I just updated the code. See https://github.com/bcwik9/robinhood-on-rails/issues/50#issuecomment-620230682

**Comment by frakman1** [comment]
> I just updated the code. See #50 (comment)

Like a boss!
