### ISSUE TITLE
Run in a Docker container

### ISSUE THREAD

**Issue by j6k4m8** [bcwik9/robinhood-on-rails#4]
I'll claim implementing this one unless someone else feels strongly about it :) 

Wanted to post first in case there's a reason you see why _not_ to do this.

**Comment by bcwik9** [comment]
I don't have a lot of experience with Docker, so go for it!

**Comment by cdtweb** [comment]
If you could dockerize this app, that would be amazing.

**Comment by j6k4m8** [comment]
@cdtweb See #6 :)

**Comment by bcwik9** [comment]
I merged the changes to master branch. Thanks!
