### ISSUE TITLE
bug: login just redirects

### ISSUE THREAD

**Issue by azah** [bcwik9/robinhood-on-rails#40]
upon hitting the login button, the request POSTs and then 302s to localhost.

**Comment by bcwik9** [comment]
Robinhood has recently [stopped supporting a lot of their API](https://github.com/sanko/Robinhood#notice-consider-this-project-dead) (not that they ever were _really_ supporting it). I can take a look at getting logins going again but, unfortunately, I wouldn't count on this project being supported much longer.

It looks like new challenges were introduced recently which changed the login flow, along with other restrictions. I'll take a look...

**Comment by azah** [comment]
Ah, fair enough. Thanks anyway!

**Comment by bcwik9** [comment]
`master` branch has been updated to support the newest login auth scheme
