### ISSUE TITLE
Two-factor authentication

### ISSUE THREAD

**Issue by dtown1984** [bcwik9/robinhood-on-rails#5]
Just ran into this. If I have two-factor authentication enabled, it will not log you in unless you disable that option in robinhood.(not sure if I put this in the right spot, I don't generally use github, app looks awesome btw!)

**Comment by bcwik9** [comment]
Thanks for pointing that out! This dashboard currently doesn't support two-factor auth, but I'll look to add that ASAP.

**Comment by bcwik9** [comment]
@dtown1984 I just added support for multifactor authentication. Try and out and feel free to reopen the issue if there's an problem or it doesn't work.
